export const STATES_LIST = [
  { label: 'All', value: 'All' },
  { label: 'All India', value: 'all_indias' },
  { label: 'AFMS', value: 'afms' },
  { label: 'DNB', value: 'dnbs' },
  { label: 'NEIGRIHMS', value: 'neigrihms' },
  { label: 'Open States', value: 'open_states' },
  { label: 'Andaman and Nicobar Islands', value: 'Andaman and Nicobar Islands' },
  { label: 'Andhra Pradesh', value: 'andhra_pradeshes' },
  { label: 'Arunachal Pradesh', value: 'arunachal_pradeshes' },
  { label: 'Assam', value: 'assams' },
  { label: 'Bihar', value: 'bihars' },
  { label: 'Chandigarh', value: 'chandigarhs' },
  { label: 'Chhattisgarh', value: 'chhattisgarhs' },
  { label: 'Dadra and Nagar Haveli', value: 'Dadra and Nagar Haveli' },
  { label: 'Delhi', value: 'delhis' },
  { label: 'Goa', value: 'goas' },
  { label: 'Gujarat', value: 'gujarats' },
  { label: 'Haryana', value: 'haryanas' },
  { label: 'Himachal Pradesh', value: 'himachal_pradeshes' },
  { label: 'Jammu & Kashmir', value: 'jammu_and_kashmirs' },
  { label: 'Jharkhand', value: 'jharkhands' },
  { label: 'Karnataka', value: 'karnatakas' },
  { label: 'Kerala', value: 'kerlas' },
  { label: 'Madhya Pradesh', value: 'madhya_pradeshes' },
  { label: 'Maharashtra', value: 'maharashtras' },
  { label: 'Manipur', value: 'manipurs' },
  { label: 'Meghalaya', value: 'Meghalaya' },
  { label: 'Mizoram', value: 'Mizoram' },
  { label: 'Nagaland', value: 'Nagaland' },
  { label: 'Odisha', value: 'odishas' },
  { label: 'Puducherry', value: 'pondicherries' },
  { label: 'Punjab', value: 'punjabs' },
  { label: 'Rajasthan', value: 'rajasthans' },
  { label: 'Sikkim', value: 'sikkims' },
  { label: 'Tamil Nadu', value: 'tamil_nadus' },
  { label: 'Telangana', value: 'telanganas' },
  { label: 'Tripura', value: 'tripuras' },
  { label: 'Uttar Pradesh', value: 'uttar_pradeshes' },
  { label: 'Uttarakhand', value: 'uttarakhands' },
  { label: 'West Bengal', value: 'west_bengals' },
]
